#!/usr/bin/python2
import sys
import xmlrpclib
import datetime
import logging
import argparse

BLANK_PKGBUILD = """
#Automatically generated by pip2arch on {date}

pkgname={pkg.name}
pkgver={pkg.version}
pkgrel=1
pkgdesc="{pkg.description}"
url="{pkg.url}"
depends=('{pkg.pyversion}')
license=('{pkg.license}')
arch=('any')
source=('{pkg.download_url}')
md5sums=('{pkg.md5}')

build() {{
    cd $srcdir/{pkg.name}-{pkg.version}
    python2 setup.py install --root="$pkgdir" || return 1
}}
"""

class pip2archException(Exception): pass
class VersionNotFound(pip2archException): pass
class LackOfInformation(pip2archException): pass

class Package(object):
    logging.info('Creating Server Proxy object')
    client = xmlrpclib.ServerProxy('http://pypi.python.org/pypi')
    
    def get_package(self, package_name, version=None):
        if version is None:
            versions = self.client.package_releases(package_name)
            version = self.choose_version(versions)
        self.version = version
        
        data = self.client.release_data(package_name, version)
        logging.info('Got release_data from PiPy')
        raw_urls = self.client.release_urls(package_name, version)
        logging.info('Got release_urls from PiPy')
        if not len(raw_urls) and len(data):
            raise LackOfInformation('PyPi did not return the neccisary information to create the PKGBUILD')
        elif len(data) and len(raw_urls):
            urls = {}
            for url in raw_urls:
                #if probabaly posix compat
                if url['filename'].endswith('.tar.gz'):
                    urls = url
            if not urls:
                raise pip2archException('Selected package version had no .tar.gz sources')
        elif not len(data):
            raise VersionNotFound('PyPi did not return any information for version {0}'.format(self.version))
        logging.info('Parsed release_urls data')
            
        
        pyversion = urls.get('python_version', '')
        if pyversion in ('source', 'any'):
            self.pyversion = 'python2'
        if pyversion.startswith('3'):
            self.pyversion = 'python'
        else:
            self.pyversion = 'python2'
            logging.info('Falling back to default python version')
        logging.info('Parsed python_version')
        
        try:
            self.name = data['name']
            self.description = data['summary']
            self.download_url = urls.get('url', '')
            self.md5 = urls['md5_digest']
            self.url = data.get('home_page', '')
            self.license = data['license']
        except KeyError:
            raise pip2archException('PiPy did not return needed information')
        logging.info('Parsed other data')
    
    def choose_version(self, versions):
        print "Multiple versions found:"
        print ', '.join(versions)
        ver = raw_input('Which version would you like to use? ')
        if ver in versions:
            return ver
        else:
            print 'That was NOT one of the choices...'
            print 'Try again'
            self.choose_version(versions)
    
    def render(self):
        return BLANK_PKGBUILD.format(pkg=self, date=datetime.date.today())


if __name__ == '__main__':
    
    
    parser = argparse.ArgumentParser(description='Convert a PiPy package into an Arch Linux PKGBUILD.')
    parser.add_argument('pkgname', metavar='N', action='store',
                        help='Name of PyPi package for pip2arch to process')
    parser.add_argument('-v', '--version', dest='version', action='store',
                        help='The version of the speciied PyPi package to process')
    parser.add_argument('-o', '--output', dest='outfile', action='store', type=argparse.FileType('w'),
                        default=open('PKGBUILD', 'w'),
                        help='The file to output the generated PKGBUILD to')
    
    args = parser.parse_args()
    
    p = Package()
    try:
        p.get_package(args.pkgname, args.version)
    except pip2archException as e:
        sys.exit('ERROR: {0}'.format(e))
    print "Got package information"
    args.outfile.write(p.render())
    print "Written PKGBUILD"